---
- name: Watchtower Docker Container
  docker_container:
    name: watchtower
    image: containrrr/watchtower
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      WATCHTOWER_CLEANUP: "{{ watchtower_cleanup }}"
      WATCHTOWER_REMOVE_VOLUMES: "{{ watchtower_remove_volumes }}"
      WATCHTOWER_DEBUG: "{{ watchtower_debug }}"
      WATCHTOWER_INCLUDE_STOPPED: "{{ watchtower_include_stopped }}"
      WATCHTOWER_REVIVE_STOPPED: "{{ watchtower_revive_stopped }}"
      WATCHTOWER_MONITOR_ONLY: "{{ watchtower_monitor_only }}"
      WATCHTOWER_NO_RESTART: "{{ watchtower_no_restart }}"
      WATCHTOWER_NO_PULL: "{{ watchtower_no_pull }}"
      WATCHTOWER_SCHEDULE: "{{ watchtower_schedule }}"
      WATCHTOWER_TIMEOUT: "{{ watchtower_timeout }}"
      WATCHTOWER_NOTIFICATIONS: "{{ watchtower_notifications }}"
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: "{{ watchtower_notification_email_from }}"
      WATCHTOWER_NOTIFICATION_EMAIL_TO: "{{ watchtower_notification_email_to }}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: "{{ watchtower_notification_email_server }}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY: "{{ watchtower_notification_email_server_tls_skip_verify }}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: "{{ watchtower_notification_email_server_port }}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: "{{ watchtower_notification_email_server_user }}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: "{{ watchtower_notification_email_server_password }}"
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: "{{ watchtower_notification_email_delay }}"
      WATCHTOWER_NOTIFICATION_GOTIFY_URL: "{{ watchtower_notification_gotify_url }}"
      WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN: "{{ watchtower_notification_gotify_token }}"
      WATCHTOWER_NOTIFICATION_MSTEAMS_HOOK_URL: "{{ watchtower_notifications_msteams_hook_url }}"
      WATCHTOWER_NOTIFICATION_MSTEAMS_USE_LOG_DATA: "{{ watchtower_notifications_msteams_use_log_data }}"
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: "{{ watchtower_notifications_slack_hook_url }}"
      WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: "{{ watchtower_notifications_slack_identifier }}"
      WATCHTOWER_NOTIFICATION_SLACK_CHANNEL: "{{ watchtower_notifications_slack_channel }}"
      WATCHTOWER_NOTIFICATION_SLACK_ICON_EMOJI: "{{ watchtower_notifications_slack_icon_emoji }}"
      WATCHTOWER_NOTIFICATION_SLACK_ICON_URL: "{{ watchtower_notifications_slack_icon_url }}"
      restart_policy: unless-stopped
    memory: 1g
